notifications:
  email: false

language: node_js
node_js: 9
cache:
  directories:
    - ~/.npm

branches:
  only:
  - master
  - /^greenkeeper/.*$/
  except:
    - /^v\d+\.\d+\.\d+$/

install: yarn

script:
- npm run build
- npm run test

before_deploy:
- npm install semantic-release -D
- npm install @semantic-release/commit-analyzer -D
- npm install @semantic-release/release-notes-generator -D
- npm install @semantic-release/changelog -D
- npm install @semantic-release/git -D
- npm install @semantic-release/github -D
- npm install @semantic-release/npm -D

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
