notifications:
  email: false

language: node_js
node_js: 9
# cache:
#   directories:
#     - ~/.npm

branches:
  only:
  - master
  - /^greenkeeper/.*$/
  except:
    - /^v\d+\.\d+\.\d+$/

# before_install:
#     - npm install -g gulp-cli

install: npm install

script:
- npm run build
- npm run test

deploy:
  provider: script
  skip_cleanup: true
  script:
  - npm i semantic-release
  - npm i @semantic-release/release-notes-generator
  - npm i @semantic-release/changelog
  - npm i @semantic-release/git @semantic-release/github
  - npm i @semantic-release/npm
    # run
    - npx semantic-release
